version: '3'

services:

  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: lottery
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./db-prepare/init.sql:/docker-entrypoint-initdb.d/init.sql